version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  disable:
    - containedctx
    - cyclop
    - funlen
    - nestif
    - depguard # (replaced by gomodguard) Go linter that checks if package imports are in a list of acceptable packages
    - exhaustruct # checks if all structure fields are initialized (really useful?)
    - forbidigo # (don't need for a CLI) Forbids identifiers
    - forcetypeassert # (replaced by errcheck) finds missing type assertions
    - godox # detection of FIXME, TODO and other comment keywords
    - paralleltest # (do not want to force this) detects missing usage of t.Parallel() method in your Go test
    - prealloc # (premature optimization) finds slice declarations that could potentially be preallocated
    - promlinter # (no prometheus here) check Prometheus metrics naming via promlint
    - thelper # (useful, but needs some configuration) detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - wrapcheck # (many detects, really useful?) checks that errors returned from external packages are wrapped
    - wsl # (too strict) forces you to use empty lines
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - funcorder
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    cyclop:
      max-complexity: 15
      package-average: 10
    errcheck:
      check-type-assertions: true
    mnd:
      ignored-functions:
        - os.Chmod
        - os.Mkdir
        - os.MkdirAll
        - os.OpenFile
        - os.WriteFile
        - flag.IntVar
        - time.Sleep
        - time.Duration
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
    tagliatelle:
      case:
        rules:
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - goconst
          - lll
        path: _test\.go
      - linters:
          - tagliatelle
        source: access_token|refresh_token|id_token|expires_in|token_type
      - linters:
          - reassign
        path: main\.go
    paths:
      - .github
      - build
      - configs
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .github
      - build
      - configs
