---
logging:
  level: info

database:
  host: 127.0.0.1
  port: 5432
  database: cardmanager
  username: changeit
  password: changeit

server:
  mode: prod
  port: 8080
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

auth:
  test_mode: false
  user_id: tester
  user_email: tester@localhost
  login_url: /login
  logout_url: /logout

probes:
  port: 8081

images:
  host: http://localhost:8080
