---
logging:
  level: INFO

database:
  host: 127.0.0.1
  port: 5432
  database: cardmanager
  username: changeit
  password: changeit

server:
  port: 8080
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  cookie:
    # must be a 32 character string
    encryption_key: "12345678901234567890123456789012"

probes:
  port: 8081

oidc:
  session_cookie_name: SESSION
  state_cookie_age: 60s
  provider:
    google:
      redirect_uri: http://localhost:3000/api/v1/login/google/callback
      client_id: "<client-id>"
      secret: "<client-secret>"

images:
  host: http://localhost:8080
