---
logging:
  level: INFO

database:
  host: 127.0.0.1
  port: 15432
  database: cardmanager
  username: tester
  password: tester

server:
  port: 3000
  cookie:
    # must be a 32 character string
    encryption_key: ""

oidc:
  session_cookie_name: SESSION
  state_cookie_age: 60s
  provider:
    google:
      redirect_uri: http://localhost:3000/api/v1/login/google/callback
      client_id: "<client-id>"
      secret: "<client-secret>"

images:
  host: http://localhost:8080
