name: Tests
on:
  push:
    branches: [ main ]
  pull_request:

env:
  GO_VERSION: 1.21

permissions:
  contents: read

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go build
        run: go build -v ./...

      - name: Go run all tests
        run: go test --count=1 ./...
